from enum import Enum


class EventType(str, Enum):
    PIVOT_HIGH = "PIVOT_HIGH"
    PIVOT_LOW = "PIVOT_LOW"
    SWING_HIGH = "SWING_HIGH"
    SWING_LOW = "SWING_LOW"
    RANGE_EXPANSION = "RANGE_EXPANSION"
    RANGE_CONTRACTION = "RANGE_CONTRACTION"
    LARGE_CANDLE = "LARGE_CANDLE"
    SMALL_CANDLE = "SMALL_CANDLE"
